"""scott was here

Revision ID: 0fcdb9876e51
Revises: 369a742db2fa
Create Date: 2018-12-28 09:17:55.018431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcdb9876e51'
down_revision = '369a742db2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'prompt_words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('prompt_words', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
