"""updated schema

Revision ID: 369a742db2fa
Revises: ecbdf6b65caa
Create Date: 2018-12-27 15:55:49.900240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369a742db2fa'
down_revision = 'ecbdf6b65caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('adjective', sa.String(length=128), nullable=True))
    op.add_column('prompts', sa.Column('noun', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'noun')
    op.drop_column('prompts', 'adjective')
    # ### end Alembic commands ###
